backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"      # Where uploaded images are stored in the repo
public_folder: "/images/uploads"    # How uploaded images are referenced in your site

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "home"
        file: "index.html"
        fields:
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Body", name: "body", widget: "markdown", required: false}
